# Generated by Django 5.0.1 on 2024-01-25 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_video_time_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_post',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
